### ISSUE TITLE
404 Not Found after using the library

### ISSUE THREAD

**Issue by AliKarimiENT** [creativecreatorormaybenot/url_strategy#43]
Hello,
I added the library to the project, called the method, and also set the base href on index.html.

main method
`setPathUrlStrategy();
`
and 
`  <base href="/">
`

after it was added when the user wanted to redirect or open a URL before this it works but now 
I face this issue

<img width="1376" alt="Screenshot 2024-08-13 at 11 50 27 PM" src="https://github.com/user-attachments/assets/54f61e82-cc2d-4048-ba53-4a00087948a5">

**Comment by Sese-Schneider** [comment]
Hey @AliKarimiENT

This issue is outside of our control. 
It looks like your webserver doesn't properly rewrite all URL paths to the `index.html`.
Only when this is done the internal routing of the Flutter engine is used.
